// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtvr94XC7wHNsJ3ZDthbGQM7_334Arrt8',
    appId: '1:471520380013:web:54c91f0ab2984256eceb64',
    messagingSenderId: '471520380013',
    projectId: 'practice-8df12',
    authDomain: 'practice-8df12.firebaseapp.com',
    storageBucket: 'practice-8df12.appspot.com',
    measurementId: 'G-BZ3K2H59J3',
    databaseURL: 'https://practice-8df12-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVCM6uWJyt3iTR0yvuQ9lW_vtGDOMvLw',
    appId: '1:471520380013:android:5f873df4eaa25976eceb64',
    messagingSenderId: '471520380013',
    projectId: 'practice-8df12',
    storageBucket: 'practice-8df12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChGN_rVJmHkcF-yeEoAQvOVz0XJADN5oI',
    appId: '1:471520380013:ios:f77c407b705f5f29eceb64',
    messagingSenderId: '471520380013',
    projectId: 'practice-8df12',
    storageBucket: 'practice-8df12.appspot.com',
    iosClientId: '471520380013-lgfupa4skmpv02a1p4jgl16fhkj4a6n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChGN_rVJmHkcF-yeEoAQvOVz0XJADN5oI',
    appId: '1:471520380013:ios:095caea15630f9e2eceb64',
    messagingSenderId: '471520380013',
    projectId: 'practice-8df12',
    storageBucket: 'practice-8df12.appspot.com',
    iosClientId: '471520380013-vkljj0fftfnf8icapru6e4o3r5nov1j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
